# Site settings
title: Photos-Graphein
email: fotos.graphein@gmail.com
description: > #
  

# Network settings
baseurl: ""
url: "http://photos-graphein.fr"

# Social networks
instagram_username:  photos_graphein
facebook_username:  FotosGraphein

# Build settings
markdown: kramdown
permalink: pretty
